name: food_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dots_indicator: ^4.0.1
  flutter:
    sdk: flutter
  get: ^4.7.2
  intl: ^0.20.2
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/image/
fonts:
  - family: Roboto
    fonts:
      - asset: assets/font/Roboto-Regular.ttf
        weight: 400
      - asset: assets/font/Roboto-Medium.ttf
        weight: 400
      - asset: assets/font/Roboto-Bold.ttf
        weight: 400
      - asset: assets/font/Roboto-Black.ttf
        weight: 400
